import 'dart:convert';
import 'dart:typed_data';

import 'dart:ui';

import 'package:umbra_flutter/umbra_flutter.dart';

/// {@template my_shader}
/// A Dart Shader class for the `my_shader` shader.
/// {@endtemplate}
class MyShader extends UmbraShader {
  MyShader._() : super(_cachedProgram!);

  /// {@macro my_shader}
  static Future<MyShader> compile() async {
    try {
      // Caching the program on the first compile call.
      _cachedProgram ??= await FragmentProgram.compile(
        spirv: Uint8List.fromList(base64Decode(_spirv)).buffer,
      );

      return MyShader._();
    } on Exception catch (err, stackTrace) {
      throw UmbraException(err, stackTrace);
    }
  }

  static FragmentProgram? _cachedProgram;

  Shader shader({
    required Size resolution,
    required Vector3 color,
  }) {
    return program.shader(
      floatUniforms: Float32List.fromList([
        color.x,
        color.y,
        color.z,
        resolution.width,
        resolution.height,
      ]),
      samplerUniforms: [],
    );
  }
}

const _spirv =
    'AwIjBwAAAQAKAA0AKwAAAAAAAAARAAIAAQAAAAsABgABAAAAR0xTTC5zdGQuNDUwAAAAAA4AAwAAAAAAAQAAAA8ABwAEAAAABAAAAG1haW4AAAAAHAAAACQAAAAQAAMABAAAAAgAAAADAAMAAQAAAEABAAAEAAoAR0xfR09PR0xFX2NwcF9zdHlsZV9saW5lX2RpcmVjdGl2ZQAABAAIAEdMX0dPT0dMRV9pbmNsdWRlX2RpcmVjdGl2ZQAFAAQABAAAAG1haW4AAAAABQAHAA0AAABmcmFnbWVudCh2ZjI7dmYyOwAAAAUAAwALAAAAdXYAAAUABQAMAAAAZnJhZ0Nvb3JkAAAABQAEABEAAABjb2xvcgAAAAUAAwAaAAAAdXYAAAUABgAcAAAAZ2xfRnJhZ0Nvb3JkAAAAAAUABQAgAAAAcmVzb2x1dGlvbgAABQAEACQAAABfQ09MT1JfAAUABAAlAAAAcGFyYW0AAAAFAAQAJwAAAHBhcmFtAAAARwADAA0AAAAAAAAARwADAAsAAAAAAAAARwADAAwAAAAAAAAARwADABEAAAAAAAAARwAEABEAAAAeAAAAAAAAAEcAAwASAAAAAAAAAEcAAwAUAAAAAAAAAEcAAwAVAAAAAAAAAEcAAwAWAAAAAAAAAEcAAwAXAAAAAAAAAEcAAwAaAAAAAAAAAEcABAAcAAAACwAAAA8AAABHAAMAIAAAAAAAAABHAAQAIAAAAB4AAAABAAAARwADACEAAAAAAAAARwADACQAAAAAAAAARwAEACQAAAAeAAAAAAAAAEcAAwAlAAAAAAAAAEcAAwAmAAAAAAAAAEcAAwAnAAAAAAAAAEcAAwAqAAAAAAAAABMAAgACAAAAIQADAAMAAAACAAAAFgADAAYAAAAgAAAAFwAEAAcAAAAGAAAAAgAAACAABAAIAAAABwAAAAcAAAAXAAQACQAAAAYAAAAEAAAAIQAFAAoAAAAJAAAACAAAAAgAAAAXAAQADwAAAAYAAAADAAAAIAAEABAAAAAAAAAADwAAADsABAAQAAAAEQAAAAAAAAArAAQABgAAABMAAAAAAIA/IAAEABsAAAABAAAACQAAADsABAAbAAAAHAAAAAEAAAAgAAQAHwAAAAAAAAAHAAAAOwAEAB8AAAAgAAAAAAAAACAABAAjAAAAAwAAAAkAAAA7AAQAIwAAACQAAAADAAAANgAFAAIAAAAEAAAAAAAAAAMAAAD4AAIABQAAADsABAAIAAAAGgAAAAcAAAA7AAQACAAAACUAAAAHAAAAOwAEAAgAAAAnAAAABwAAAD0ABAAJAAAAHQAAABwAAABPAAcABwAAAB4AAAAdAAAAHQAAAAAAAAABAAAAPQAEAAcAAAAhAAAAIAAAAIgABQAHAAAAIgAAAB4AAAAhAAAAPgADABoAAAAiAAAAPQAEAAcAAAAmAAAAGgAAAD4AAwAlAAAAJgAAAD0ABAAJAAAAKAAAABwAAABPAAcABwAAACkAAAAoAAAAKAAAAAAAAAABAAAAPgADACcAAAApAAAAOQAGAAkAAAAqAAAADQAAACUAAAAnAAAAPgADACQAAAAqAAAA/QABADgAAQA2AAUACQAAAA0AAAAAAAAACgAAADcAAwAIAAAACwAAADcAAwAIAAAADAAAAPgAAgAOAAAAPQAEAA8AAAASAAAAEQAAAFEABQAGAAAAFAAAABIAAAAAAAAAUQAFAAYAAAAVAAAAEgAAAAEAAABRAAUABgAAABYAAAASAAAAAgAAAFAABwAJAAAAFwAAABQAAAAVAAAAFgAAABMAAAD+AAIAFwAAADgAAQA=';
